title: 'Hadron'
default_lang: de
author:
  name: 'Crabston GmbH'
  email: hadron@crabston.dev
taxonomies:
  - category
  - tag
  - month
  - author
  - filter
metadata:
  description: 'Hadron ist ein Grav Theme und Skeleton, das f端r Einsteiger als Vorlage f端r Website uns Webshops dient, aber auch f端r Profis als Basis f端r komplexe Projekte genutzt werden kann.'
  keywords: 'grav, theme, skeleton, hadron, website, webshop'
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: '/blog'
