streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '':
          - user/themes/hadron
          - user/themes/quark

grid-size: grid-lg
blog-page: /blog
hide_title: true
dropdown:
  enabled: true
custommenus:
  enabled: false
menu:
  - text: Grav
    icon: external-link
    url: 'https://getgrav.org/'
    target: _blank
langswitcher:
  enable: true
  display: inline
  format: icon
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
spectre:
  exp: false
  icons: false
production-mode: true
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
fontawesome:
  solid: false
  regular: false
  brands: false
  brand: false
blog_page_hero_classes: 'text-light title-h1h2 overlay-dark-gradient hero-large parallax'
invert_logo: true
favicon:
  user/themes/hadron/images/hadron-favicon.svg:
    name: hadron-favicon.svg
    full_path: hadron-favicon.svg
    type: image/svg+xml
    size: 566
    path: user/themes/hadron/images/hadron-favicon.svg
custom_logo:
  user/themes/hadron/images/logo/hadron-logo.svg:
    name: hadron-logo.svg
    full_path: hadron-logo.svg
    type: image/svg+xml
    size: 3076
    path: user/themes/hadron/images/logo/hadron-logo.svg
custom_logo_mobile:
  user/themes/hadron/images/logo/hadron-logo.svg:
    name: hadron-logo.svg
    full_path: hadron-logo.svg
    type: image/svg+xml
    size: 3076
    path: user/themes/hadron/images/logo/hadron-logo.svg
