streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/hadron, user/themes/quark]
grid-size: grid-lg
blog-page: /blog
hide_title: true
dropdown:
  enabled: true
custommenus:
  enabled: false
menu:
  -
    text: Grav
    icon: external-link
    url: 'https://getgrav.org/'
    target: _blank
langswitcher:
  enable: false
  display: inline
  format: icon
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
spectre:
  exp: false
  icons: false
production-mode: true
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
fontawesome:
  solid: false
  regular: false
  brands: false
  brand: false
blog_page_hero_classes: 'text-light title-h1h2 overlay-dark-gradient hero-large parallax'
invert_logo: false
favicon:
  user/themes/hadron/images/logo.png:
    name: logo.png
    full_path: logo.png
    type: image/png
    size: 37424
    path: user/themes/hadron/images/logo.png
custom_logo:
  user/themes/hadron/images/logo/0000.png:
    name: 0000.png
    full_path: 0000.png
    type: image/png
    size: 23206
    path: user/themes/hadron/images/logo/0000.png
custom_logo_mobile:
  user/themes/hadron/images/logo/0000.png:
    name: 0000.png
    full_path: 0000.png
    type: image/png
    size: 23206
    path: user/themes/hadron/images/logo/0000.png
